# Generated by Django 5.0 on 2023-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'administradores',
                'managed': False,
            },
        ),
    ]
